name: sum_ffi
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  ffi: ^1.0.0
  path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
